'use client';

import { useState } from 'react';
import { Activity, Bell, Building2, Check, Download, FileText, Lock, Search, Settings, Smartphone, UserCog, X, Zap } from 'lucide-react';
import { Card, PageContainer, PageHeader, RiskBadge, StatusBadge, TableContainer, Td, Th } from '@/components/shared/page-primitives';
import { alerts, auditLogs, devices, reports, rolePermissions, settingsSections, users, formatINR } from '@/lib/demo-data';

const buttonClass = 'px-2.5 py-1.5 text-[11px] font-mono-tech rounded border border-lg text-lg-muted hover:text-white hover:border-blue-500/30 transition-colors';

export function AlertsWorkspace() {
  const [severity, setSeverity] = useState('All');
  const filtered = alerts.filter(a => severity === 'All' || a.severity === severity.toLowerCase());
  return <PageContainer><PageHeader title="Threat & Alert Center" subtitle="Prioritized signals across your payment ecosystem" icon={Bell} />
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{['critical','high','medium','low'].map(level => <Card key={level}><div className="text-[10px] uppercase font-mono-tech text-lg-muted">{level} alerts</div><div className="text-2xl font-bold text-white mt-1">{alerts.filter(a=>a.severity===level).length}</div></Card>)}</div>
    <div className="flex gap-2">{['All','Critical','High','Medium','Low'].map(s=><button key={s} onClick={()=>setSeverity(s)} className={`${buttonClass} ${severity===s?'text-lg-blue border-blue-500/30 bg-blue-500/10':''}`}>{s}</button>)}</div>
    <Card title="Active Threat Signals" subtitle={`${filtered.length} alerts requiring attention`}><TableContainer><thead><tr><Th>Severity</Th><Th>Alert ID</Th><Th>Time</Th><Th>Signal</Th><Th>Affected transactions</Th><Th>Exposure</Th><Th>AI explanation</Th><Th>Recommended action</Th></tr></thead><tbody>{filtered.map(a=><tr key={a.id} className="border-b border-lg/50"><Td><StatusBadge status={a.severity.charAt(0).toUpperCase() + a.severity.slice(1)}/></Td><Td className="font-mono-tech text-white/80">{a.id}</Td><Td className="font-mono-tech text-lg-muted">{a.time}</Td><Td className="text-white">{a.type}</Td><Td className="text-lg-muted">12–87</Td><Td className="font-mono-tech text-amber-400">{formatINR(a.exposure)}</Td><Td className="text-white/70 max-w-xs">{a.message}</Td><Td><button className={buttonClass}>Investigate</button></Td></tr>)}</tbody></TableContainer></Card>
  </PageContainer>;
}

export function DeviceWorkspace() {
  const [selected, setSelected] = useState(devices[0]);
  return <PageContainer><PageHeader title="Device Intelligence" subtitle="Fingerprint activity, relationships and device risk" icon={Smartphone} />
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Tracked devices','1,842'],['High risk','86'],['New today','24'],['Shared networks','137']].map(([l,v])=><Card key={l}><div className="text-[10px] uppercase font-mono-tech text-lg-muted">{l}</div><div className="text-2xl font-bold text-white mt-1">{v}</div></Card>)}</div>
    <div className="grid lg:grid-cols-3 gap-4"><Card title="Device Registry" subtitle="Select a device for relationship intelligence" className="lg:col-span-2"><TableContainer><thead><tr><Th>Device ID</Th><Th>First seen</Th><Th>Last seen</Th><Th>Accounts</Th><Th>Transactions</Th><Th>Risk</Th><Th>Locations</Th></tr></thead><tbody>{devices.map(d=><tr key={d.id} onClick={()=>setSelected(d)} className={`border-b border-lg/50 cursor-pointer hover:bg-white/[0.02] ${selected.id===d.id?'bg-blue-500/5':''}`}><Td className="font-mono-tech text-white">{d.id}</Td><Td className="text-lg-muted">{d.firstSeen}</Td><Td className="text-lg-muted">{d.lastSeen}</Td><Td>{d.accounts}</Td><Td>{d.transactions}</Td><Td><RiskBadge score={d.riskScore} level={d.riskScore>80?'critical':d.riskScore>60?'high':d.riskScore>40?'medium':'low'}/></Td><Td className="text-lg-muted">{d.locations}</Td></tr>)}</tbody></TableContainer></Card>
      <Card title="Device Relationship Graph" subtitle={selected.id}><div className="h-56 rounded border border-blue-500/10 bg-blue-500/[0.02] relative overflow-hidden lg-grid-bg"><div className="absolute inset-0 flex items-center justify-center"><div className="w-16 h-16 rounded-full border border-rose-500/40 bg-rose-500/10 flex items-center justify-center text-[10px] font-mono-tech text-rose-300">{selected.id}</div>{['ACCOUNT','IP','TXN','LOCATION'].map((n,i)=><div key={n} className={`absolute text-[10px] font-mono-tech text-lg-blue ${['top-5 left-8','top-8 right-8','bottom-8 left-10','bottom-5 right-8'][i]}`}>{n}<span className="block w-14 h-px bg-blue-500/30 mt-1"/></div>)}</div></div><div className="mt-3 text-[11px] text-white/70">Linked to {selected.accounts} accounts across {selected.ips} IP addresses. Locations: {selected.locations}.</div></Card></div>
  </PageContainer>;
}

export function ReportsWorkspace() {
  const [message, setMessage] = useState('');
  return <PageContainer><PageHeader title="Reports Center" subtitle="Generate and distribute governed intelligence reports" icon={FileText} /><Card title="Available reports" subtitle="Synthetic demo catalog"><TableContainer><thead><tr><Th>Report</Th><Th>Type</Th><Th>Status</Th><Th>Generated</Th><Th>Size</Th><Th>Actions</Th></tr></thead><tbody>{reports.map(r=><tr key={r.id} className="border-b border-lg/50"><Td className="text-white">{r.name}</Td><Td className="text-lg-muted">{r.type}</Td><Td><StatusBadge status={r.status}/></Td><Td className="text-lg-muted">{r.date}</Td><Td className="font-mono-tech text-lg-muted">{r.size}</Td><Td className="flex gap-1.5"><button onClick={()=>setMessage(`Previewing ${r.id}`)} className={buttonClass}>Preview</button><button onClick={()=>setMessage(`Export queued for ${r.id}`)} className={buttonClass}><Download size={12}/></button><button onClick={()=>setMessage(`Schedule editor opened for ${r.id}`)} className={buttonClass}>Schedule</button></Td></tr>)}</tbody></TableContainer>{message&&<div className="mt-3 text-[11px] text-lg-blue">{message}</div>}</Card><div className="grid md:grid-cols-3 gap-4">{['Risk Summary','Revenue Recovery Report','Executive Report'].map((name,i)=><Card key={name} title={name}><p className="text-[11px] text-lg-muted mb-3">Last period performance and decision-ready highlights.</p><button onClick={()=>setMessage(`Generating ${name}`)} className={`${buttonClass} text-lg-blue border-blue-500/20`}>Generate now</button></Card>)}</div></PageContainer>;
}

export function UsersWorkspace() {
  const [showAdd, setShowAdd] = useState(false);
  return <PageContainer><PageHeader title="User & Access Management" subtitle="Govern identities, roles and permissions" icon={UserCog}/><div className="flex justify-end"><button onClick={()=>setShowAdd(true)} className={`${buttonClass} text-lg-blue border-blue-500/30`}>+ Add User</button></div><Card title="Workspace users" subtitle={`${users.length} provisioned identities`}><TableContainer><thead><tr><Th>User</Th><Th>Role</Th><Th>Status</Th><Th>Last active</Th><Th>Created</Th><Th>Actions</Th></tr></thead><tbody>{users.map(u=><tr key={u.email} className="border-b border-lg/50"><Td><div className="text-white">{u.name}</div><div className="text-lg-muted">{u.email}</div></Td><Td className="text-lg-blue">{u.role}</Td><Td><StatusBadge status={u.status}/></Td><Td className="text-lg-muted">{u.lastLogin}</Td><Td className="text-lg-muted">{u.created}</Td><Td><button className={buttonClass}>Edit</button><button className={`${buttonClass} ml-1`}>{u.status==='Active'?'Suspend':'Restore'}</button></Td></tr>)}</tbody></TableContainer></Card><Card title="Role permissions" subtitle="Least-privilege policy matrix"><TableContainer><thead><tr><Th>Capability</Th><Th>Admin</Th><Th>Analyst</Th><Th>Finance</Th><Th>Operations</Th><Th>Executive</Th></tr></thead><tbody>{rolePermissions.map(p=><tr key={p.category} className="border-b border-lg/50"><Td className="text-white">{p.category}</Td>{[p.admin,p.analyst,p.finance,p.ops,p.exec].map((v,i)=><Td key={i}>{v?<Check size={14} className="text-emerald-400"/>:<X size={14} className="text-lg-dim"/>}</Td>)}</tr>)}</tbody></TableContainer></Card>{showAdd&&<div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50"><Card title="Add user" className="w-full max-w-md"><input placeholder="Name and email" className="w-full bg-white/[0.03] border border-lg rounded p-2 text-sm text-white mb-3"/><div className="flex justify-end gap-2"><button onClick={()=>setShowAdd(false)} className={buttonClass}>Cancel</button><button onClick={()=>setShowAdd(false)} className={`${buttonClass} text-lg-blue`}>Invite user</button></div></Card></div>}</PageContainer>;
}

export function AuditWorkspace() {
  const [query,setQuery]=useState('');
  const rows=auditLogs.filter(l=>Object.values(l).some(v=>v.toLowerCase().includes(query.toLowerCase())));
  return <PageContainer><PageHeader title="Audit Logs" subtitle="Immutable decision and access trail" icon={Activity}/><div className="relative"><Search size={14} className="absolute left-3 top-2.5 text-lg-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search user, action, entity or case" className="w-full bg-lg-surface border border-lg rounded-lg pl-9 p-2 text-[12px] text-white"/></div><Card title="Event stream" subtitle={`${rows.length} events`}><TableContainer><thead><tr><Th>Timestamp</Th><Th>User</Th><Th>Role</Th><Th>Action</Th><Th>Entity</Th><Th>Case</Th><Th>Decision</Th><Th>IP</Th><Th>Result</Th></tr></thead><tbody>{rows.map((l,i)=><tr key={i} className="border-b border-lg/50"><Td className="font-mono-tech text-lg-muted">{l.time}</Td><Td className="text-white">{l.user}</Td><Td className="text-lg-muted">{l.role}</Td><Td>{l.action}</Td><Td className="font-mono-tech text-lg-blue">{l.entity}</Td><Td className="font-mono-tech text-lg-muted">{l.case}</Td><Td>{l.decision}</Td><Td className="font-mono-tech text-lg-muted">{l.ip}</Td><Td><StatusBadge status={l.result}/></Td></tr>)}</tbody></TableContainer></Card></PageContainer>;
}

export function SettingsWorkspace() {
  const [selected,setSelected]=useState(settingsSections[0].label);
  return <PageContainer><PageHeader title="Settings" subtitle="Configure LedgerGuard policies and integrations" icon={Settings}/><div className="grid lg:grid-cols-3 gap-4"><Card title="Configuration areas"><div className="space-y-1">{settingsSections.map(s=><button key={s.label} onClick={()=>setSelected(s.label)} className={`w-full text-left p-2.5 rounded text-[12px] ${selected===s.label?'bg-blue-500/10 text-white border border-blue-500/20':'text-lg-muted hover:text-white'}`}><div className="flex items-center gap-2"><Building2 size={14}/>{s.label}</div><div className="text-[10px] text-lg-dim mt-1">{s.description}</div></button>)}</div></Card><Card title={selected} subtitle="Changes are saved to the merchant workspace" className="lg:col-span-2"><div className="space-y-4"><label className="block text-[11px] text-lg-muted">Policy name<input defaultValue={selected} className="mt-1 w-full bg-white/[0.03] border border-lg rounded p-2 text-sm text-white"/></label><label className="block text-[11px] text-lg-muted">Configuration notes<textarea defaultValue="Review changes with a second administrator before publishing." className="mt-1 w-full h-24 bg-white/[0.03] border border-lg rounded p-2 text-sm text-white"/></label><div className="flex items-center gap-2 text-[11px] text-lg-muted"><Lock size={13} className="text-lg-blue"/> Admin approval required for production changes</div><button className={`${buttonClass} text-lg-blue border-blue-500/30`}>Save configuration</button></div></Card></div></PageContainer>;
}
