'use client';
import { FormEvent, useState } from 'react';
import { ShieldCheck, Eye, EyeOff, LockKeyhole } from 'lucide-react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth } from '@/lib/auth-context';

export default function LoginPage() {
  const { signIn } = useAuth(); const router = useRouter(); const params = useSearchParams();
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [remember,setRemember]=useState(true); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [show,setShow]=useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); if (await signIn(email,password,remember)) { await new Promise(r=>setTimeout(r,250)); router.replace(params.get('next') || '/overview'); } else { setError('Invalid credentials. Please verify your email and password.'); setBusy(false); } }
  return <main className="min-h-screen bg-black flex items-center justify-center p-5 lg-grid-bg"><div className="w-full max-w-md bg-lg-surface border border-lg rounded-lg p-7 shadow-2xl shadow-blue-500/5"><div className="flex items-center gap-3 mb-8"><ShieldCheck className="text-lg-blue" size={30}/><div><div className="text-lg font-bold text-white">LEDGER<span className="text-lg-blue">GUARD</span></div><div className="text-[10px] text-lg-muted font-mono-tech">FINANCIAL INTELLIGENCE PLATFORM</div></div></div><h1 className="text-xl font-semibold text-white">Secure enterprise access</h1><p className="text-[12px] text-lg-muted mt-1 mb-6">Sign in to your risk command center.</p><form onSubmit={submit} className="space-y-4"><label className="block text-[11px] text-lg-muted">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 w-full bg-white/[0.03] border border-lg rounded p-2.5 text-sm text-white focus:border-blue-500/50 outline-none" placeholder="you@company.com"/></label><label className="block text-[11px] text-lg-muted">Password<div className="relative mt-1"><input required type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} className="w-full bg-white/[0.03] border border-lg rounded p-2.5 pr-10 text-sm text-white focus:border-blue-500/50 outline-none" placeholder="••••••••"/><button type="button" aria-label="Toggle password visibility" onClick={()=>setShow(!show)} className="absolute right-2 top-2.5 text-lg-muted">{show?<EyeOff size={15}/>:<Eye size={15}/>}</button></div></label><div className="flex justify-between items-center text-[11px]"><label className="flex items-center gap-2 text-lg-muted"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/> Remember me</label><button type="button" className="text-lg-blue">Forgot password?</button></div>{error&&<div role="alert" className="text-[11px] text-rose-400 bg-rose-500/10 border border-rose-500/20 rounded p-2.5">{error}</div>}<button disabled={busy} className="w-full py-2.5 rounded bg-blue-500/15 border border-blue-500/30 text-lg-blue text-[12px] font-mono-tech hover:bg-blue-500/25 disabled:opacity-50">{busy?'AUTHENTICATING…':'SIGN IN'}</button></form><div className="flex items-center gap-2 mt-6 text-[10px] text-lg-dim font-mono-tech"><LockKeyhole size={12} className="text-emerald-400"/> ENCRYPTED SESSION · DEMO ENVIRONMENT</div></div></main>;
}
